## Aqara T1 LED Strip Segments
## Home Assistant script blueprint
##
## Install to blueprints/script/aqara/aqara_t1_strip_segments_blueprint.yaml

blueprint:
  name: Aqara T1 LED Strip - Segment Colors Script
  description: >
    Script blueprint to control individual segments on the Aqara T1 LED Strip with custom colors. 
    Each segment can be set to any color using a color picker. Set the color to black (000) to turn off a segment.
    Supports strips from 2m (10 segments) up to 10m (50 segments). Only configured segments up to strip length are sent.
    Supports multiple lights.
  domain: script
  input:
    target_lights:
      name: Target Lights
      description: >
        Select one or more T1 LED Strip lights or devices.
      selector:
        target:
          entity:
            - domain: light

    z2m_base_topic:
      name: Zigbee2MQTT Base Topic
      description: The base MQTT topic for your Zigbee2MQTT instance
      default: "zigbee2mqtt"
      selector:
        text:
    
    strip_length_entity:
      name: Strip Length Entity
      description: The number entity showing your strip's length in meters
      selector:
        entity:
          domain: number
          integration: mqtt
    
    color_01:
      name: Segment 1 Color
      description: Segment 1 (0.0-0.2m)
      default: [255, 0, 0]
      selector:
        color_rgb:
    
    color_02:
      name: Segment 2 Color
      description: Segment 2 (0.2-0.4m)
      default: [255, 127, 0]
      selector:
        color_rgb:
    
    color_03:
      name: Segment 3 Color
      description: Segment 3 (0.4-0.6m)
      default: [255, 255, 0]
      selector:
        color_rgb:
    
    color_04:
      name: Segment 4 Color
      description: Segment 4 (0.6-0.8m)
      default: [0, 255, 0]
      selector:
        color_rgb:
    
    color_05:
      name: Segment 5 Color
      description: Segment 5 (0.8-1.0m)
      default: [0, 255, 127]
      selector:
        color_rgb:
    
    color_06:
      name: Segment 6 Color
      description: Segment 6 (1.0-1.2m)
      default: [0, 255, 255]
      selector:
        color_rgb:
    
    color_07:
      name: Segment 7 Color
      description: Segment 7 (1.2-1.4m)
      default: [0, 127, 255]
      selector:
        color_rgb:
    
    color_08:
      name: Segment 8 Color
      description: Segment 8 (1.4-1.6m)
      default: [0, 0, 255]
      selector:
        color_rgb:
    
    color_09:
      name: Segment 9 Color
      description: Segment 9 (1.6-1.8m)
      default: [127, 0, 255]
      selector:
        color_rgb:
    
    color_10:
      name: Segment 10 Color
      description: Segment 10 (1.8-2.0m)
      default: [255, 0, 255]
      selector:
        color_rgb:
    
    color_11:
      name: Segment 11 Color
      description: Segment 11 (2.0-2.2m)
      default: [255, 0, 0]
      selector:
        color_rgb:
    
    color_12:
      name: Segment 12 Color
      description: Segment 12 (2.2-2.4m)
      default: [255, 127, 0]
      selector:
        color_rgb:
    
    color_13:
      name: Segment 13 Color
      description: Segment 13 (2.4-2.6m)
      default: [255, 255, 0]
      selector:
        color_rgb:
    
    color_14:
      name: Segment 14 Color
      description: Segment 14 (2.6-2.8m)
      default: [0, 255, 0]
      selector:
        color_rgb:
    
    color_15:
      name: Segment 15 Color
      description: Segment 15 (2.8-3.0m)
      default: [0, 255, 127]
      selector:
        color_rgb:
    
    color_16:
      name: Segment 16 Color
      description: Segment 16 (3.0-3.2m)
      default: [0, 255, 255]
      selector:
        color_rgb:
    
    color_17:
      name: Segment 17 Color
      description: Segment 17 (3.2-3.4m)
      default: [0, 127, 255]
      selector:
        color_rgb:
    
    color_18:
      name: Segment 18 Color
      description: Segment 18 (3.4-3.6m)
      default: [0, 0, 255]
      selector:
        color_rgb:
    
    color_19:
      name: Segment 19 Color
      description: Segment 19 (3.6-3.8m)
      default: [127, 0, 255]
      selector:
        color_rgb:
    
    color_20:
      name: Segment 20 Color
      description: Segment 20 (3.8-4.0m)
      default: [255, 0, 255]
      selector:
        color_rgb:
    
    color_21:
      name: Segment 21 Color
      description: Segment 21 (4.0-4.2m)
      default: [255, 0, 0]
      selector:
        color_rgb:
    
    color_22:
      name: Segment 22 Color
      description: Segment 22 (4.2-4.4m)
      default: [255, 127, 0]
      selector:
        color_rgb:
    
    color_23:
      name: Segment 23 Color
      description: Segment 23 (4.4-4.6m)
      default: [255, 255, 0]
      selector:
        color_rgb:
    
    color_24:
      name: Segment 24 Color
      description: Segment 24 (4.6-4.8m)
      default: [0, 255, 0]
      selector:
        color_rgb:
    
    color_25:
      name: Segment 25 Color
      description: Segment 25 (4.8-5.0m)
      default: [0, 255, 127]
      selector:
        color_rgb:
    
    color_26:
      name: Segment 26 Color
      description: Segment 26 (5.0-5.2m)
      default: [0, 255, 255]
      selector:
        color_rgb:
    
    color_27:
      name: Segment 27 Color
      description: Segment 27 (5.2-5.4m)
      default: [0, 127, 255]
      selector:
        color_rgb:
    
    color_28:
      name: Segment 28 Color
      description: Segment 28 (5.4-5.6m)
      default: [0, 0, 255]
      selector:
        color_rgb:
    
    color_29:
      name: Segment 29 Color
      description: Segment 29 (5.6-5.8m)
      default: [127, 0, 255]
      selector:
        color_rgb:
    
    color_30:
      name: Segment 30 Color
      description: Segment 30 (5.8-6.0m)
      default: [255, 0, 255]
      selector:
        color_rgb:
    
    color_31:
      name: Segment 31 Color
      description: Segment 31 (6.0-6.2m)
      default: [255, 0, 0]
      selector:
        color_rgb:
    
    color_32:
      name: Segment 32 Color
      description: Segment 32 (6.2-6.4m)
      default: [255, 127, 0]
      selector:
        color_rgb:
    
    color_33:
      name: Segment 33 Color
      description: Segment 33 (6.4-6.6m)
      default: [255, 255, 0]
      selector:
        color_rgb:
    
    color_34:
      name: Segment 34 Color
      description: Segment 34 (6.6-6.8m)
      default: [0, 255, 0]
      selector:
        color_rgb:
    
    color_35:
      name: Segment 35 Color
      description: Segment 35 (6.8-7.0m)
      default: [0, 255, 127]
      selector:
        color_rgb:
    
    color_36:
      name: Segment 36 Color
      description: Segment 36 (7.0-7.2m)
      default: [0, 255, 255]
      selector:
        color_rgb:
    
    color_37:
      name: Segment 37 Color
      description: Segment 37 (7.2-7.4m)
      default: [0, 127, 255]
      selector:
        color_rgb:
    
    color_38:
      name: Segment 38 Color
      description: Segment 38 (7.4-7.6m)
      default: [0, 0, 255]
      selector:
        color_rgb:
    
    color_39:
      name: Segment 39 Color
      description: Segment 39 (7.6-7.8m)
      default: [127, 0, 255]
      selector:
        color_rgb:
    
    color_40:
      name: Segment 40 Color
      description: Segment 40 (7.8-8.0m)
      default: [255, 0, 255]
      selector:
        color_rgb:
    
    color_41:
      name: Segment 41 Color
      description: Segment 41 (8.0-8.2m)
      default: [255, 0, 0]
      selector:
        color_rgb:
    
    color_42:
      name: Segment 42 Color
      description: Segment 42 (8.2-8.4m)
      default: [255, 127, 0]
      selector:
        color_rgb:
    
    color_43:
      name: Segment 43 Color
      description: Segment 43 (8.4-8.6m)
      default: [255, 255, 0]
      selector:
        color_rgb:
    
    color_44:
      name: Segment 44 Color
      description: Segment 44 (8.6-8.8m)
      default: [0, 255, 0]
      selector:
        color_rgb:
    
    color_45:
      name: Segment 45 Color
      description: Segment 45 (8.8-9.0m)
      default: [0, 255, 127]
      selector:
        color_rgb:
    
    color_46:
      name: Segment 46 Color
      description: Segment 46 (9.0-9.2m)
      default: [0, 255, 255]
      selector:
        color_rgb:
    
    color_47:
      name: Segment 47 Color
      description: Segment 47 (9.2-9.4m)
      default: [0, 127, 255]
      selector:
        color_rgb:
    
    color_48:
      name: Segment 48 Color
      description: Segment 48 (9.4-9.6m)
      default: [0, 0, 255]
      selector:
        color_rgb:
    
    color_49:
      name: Segment 49 Color
      description: Segment 49 (9.6-9.8m)
      default: [127, 0, 255]
      selector:
        color_rgb:
    
    color_50:
      name: Segment 50 Color
      description: Segment 50 (9.8-10.0m)
      default: [255, 0, 255]
      selector:
        color_rgb:

sequence:
  - variables:
      z2m_base_topic: !input z2m_base_topic
      target_lights: !input target_lights
      strip_length_entity: !input strip_length_entity
      c01: !input color_01
      c02: !input color_02
      c03: !input color_03
      c04: !input color_04
      c05: !input color_05
      c06: !input color_06
      c07: !input color_07
      c08: !input color_08
      c09: !input color_09
      c10: !input color_10
      c11: !input color_11
      c12: !input color_12
      c13: !input color_13
      c14: !input color_14
      c15: !input color_15
      c16: !input color_16
      c17: !input color_17
      c18: !input color_18
      c19: !input color_19
      c20: !input color_20
      c21: !input color_21
      c22: !input color_22
      c23: !input color_23
      c24: !input color_24
      c25: !input color_25
      c26: !input color_26
      c27: !input color_27
      c28: !input color_28
      c29: !input color_29
      c30: !input color_30
      c31: !input color_31
      c32: !input color_32
      c33: !input color_33
      c34: !input color_34
      c35: !input color_35
      c36: !input color_36
      c37: !input color_37
      c38: !input color_38
      c39: !input color_39
      c40: !input color_40
      c41: !input color_41
      c42: !input color_42
      c43: !input color_43
      c44: !input color_44
      c45: !input color_45
      c46: !input color_46
      c47: !input color_47
      c48: !input color_48
      c49: !input color_49
      c50: !input color_50
  
  - variables:
      # Calculate segment count from strip length
      strip_length_meters: "{{ states(strip_length_entity) | float(2.0) }}"
      segment_count: "{{ (strip_length_meters * 5) | int }}"
  
  - repeat:
      for_each: >
        {% set ns = namespace(lights=[]) %}
        {% if target_lights.entity_id is defined %}
          {% if target_lights.entity_id is string %}
            {% set ns.lights = [target_lights.entity_id] %}
          {% else %}
            {% set ns.lights = target_lights.entity_id %}
          {% endif %}
        {% endif %}
        {% if target_lights.device_id is defined %}
          {% if target_lights.device_id is string %}
            {% set device_entities = device_entities(target_lights.device_id) | select('match', '^light\\.') | list %}
            {% set ns.lights = ns.lights + device_entities %}
          {% else %}
            {% for device_id in target_lights.device_id %}
              {% set device_entities = device_entities(device_id) | select('match', '^light\\.') | list %}
              {% set ns.lights = ns.lights + device_entities %}
            {% endfor %}
          {% endif %}
        {% endif %}
        {% if target_lights.area_id is defined %}
          {% if target_lights.area_id is string %}
            {% set area_entities = area_entities(target_lights.area_id) | select('match', '^light\\.') | list %}
            {% set ns.lights = ns.lights + area_entities %}
          {% else %}
            {% for area_id in target_lights.area_id %}
              {% set area_entities = area_entities(area_id) | select('match', '^light\\.') | list %}
              {% set ns.lights = ns.lights + area_entities %}
            {% endfor %}
          {% endif %}
        {% endif %}
        {{ ns.lights | unique | list }}
      sequence:
        - variables:
            entity_device_id: "{{ device_id(repeat.item) }}"
            z2m_device_name: "{{ device_attr(entity_device_id, 'name') }}"
        
        - alias: "Set T1 Strip segment colors"
          service: mqtt.publish
          data:
            topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/set"
            payload: >
              {
                "segment_colors": [
                  {"segment": 1, "color": {"r": {{ c01[0] }}, "g": {{ c01[1] }}, "b": {{ c01[2] }}}},
                  {"segment": 2, "color": {"r": {{ c02[0] }}, "g": {{ c02[1] }}, "b": {{ c02[2] }}}},
                  {"segment": 3, "color": {"r": {{ c03[0] }}, "g": {{ c03[1] }}, "b": {{ c03[2] }}}},
                  {"segment": 4, "color": {"r": {{ c04[0] }}, "g": {{ c04[1] }}, "b": {{ c04[2] }}}},
                  {"segment": 5, "color": {"r": {{ c05[0] }}, "g": {{ c05[1] }}, "b": {{ c05[2] }}}},
                  {"segment": 6, "color": {"r": {{ c06[0] }}, "g": {{ c06[1] }}, "b": {{ c06[2] }}}},
                  {"segment": 7, "color": {"r": {{ c07[0] }}, "g": {{ c07[1] }}, "b": {{ c07[2] }}}},
                  {"segment": 8, "color": {"r": {{ c08[0] }}, "g": {{ c08[1] }}, "b": {{ c08[2] }}}},
                  {"segment": 9, "color": {"r": {{ c09[0] }}, "g": {{ c09[1] }}, "b": {{ c09[2] }}}},
                  {"segment": 10, "color": {"r": {{ c10[0] }}, "g": {{ c10[1] }}, "b": {{ c10[2] }}}},
                  {"segment": 11, "color": {"r": {{ c11[0] }}, "g": {{ c11[1] }}, "b": {{ c11[2] }}}},
                  {"segment": 12, "color": {"r": {{ c12[0] }}, "g": {{ c12[1] }}, "b": {{ c12[2] }}}},
                  {"segment": 13, "color": {"r": {{ c13[0] }}, "g": {{ c13[1] }}, "b": {{ c13[2] }}}},
                  {"segment": 14, "color": {"r": {{ c14[0] }}, "g": {{ c14[1] }}, "b": {{ c14[2] }}}},
                  {"segment": 15, "color": {"r": {{ c15[0] }}, "g": {{ c15[1] }}, "b": {{ c15[2] }}}},
                  {"segment": 16, "color": {"r": {{ c16[0] }}, "g": {{ c16[1] }}, "b": {{ c16[2] }}}},
                  {"segment": 17, "color": {"r": {{ c17[0] }}, "g": {{ c17[1] }}, "b": {{ c17[2] }}}},
                  {"segment": 18, "color": {"r": {{ c18[0] }}, "g": {{ c18[1] }}, "b": {{ c18[2] }}}},
                  {"segment": 19, "color": {"r": {{ c19[0] }}, "g": {{ c19[1] }}, "b": {{ c19[2] }}}},
                  {"segment": 20, "color": {"r": {{ c20[0] }}, "g": {{ c20[1] }}, "b": {{ c20[2] }}}},
                  {"segment": 21, "color": {"r": {{ c21[0] }}, "g": {{ c21[1] }}, "b": {{ c21[2] }}}},
                  {"segment": 22, "color": {"r": {{ c22[0] }}, "g": {{ c22[1] }}, "b": {{ c22[2] }}}},
                  {"segment": 23, "color": {"r": {{ c23[0] }}, "g": {{ c23[1] }}, "b": {{ c23[2] }}}},
                  {"segment": 24, "color": {"r": {{ c24[0] }}, "g": {{ c24[1] }}, "b": {{ c24[2] }}}},
                  {"segment": 25, "color": {"r": {{ c25[0] }}, "g": {{ c25[1] }}, "b": {{ c25[2] }}}},
                  {"segment": 26, "color": {"r": {{ c26[0] }}, "g": {{ c26[1] }}, "b": {{ c26[2] }}}},
                  {"segment": 27, "color": {"r": {{ c27[0] }}, "g": {{ c27[1] }}, "b": {{ c27[2] }}}},
                  {"segment": 28, "color": {"r": {{ c28[0] }}, "g": {{ c28[1] }}, "b": {{ c28[2] }}}},
                  {"segment": 29, "color": {"r": {{ c29[0] }}, "g": {{ c29[1] }}, "b": {{ c29[2] }}}},
                  {"segment": 30, "color": {"r": {{ c30[0] }}, "g": {{ c30[1] }}, "b": {{ c30[2] }}}},
                  {"segment": 31, "color": {"r": {{ c31[0] }}, "g": {{ c31[1] }}, "b": {{ c31[2] }}}},
                  {"segment": 32, "color": {"r": {{ c32[0] }}, "g": {{ c32[1] }}, "b": {{ c32[2] }}}},
                  {"segment": 33, "color": {"r": {{ c33[0] }}, "g": {{ c33[1] }}, "b": {{ c33[2] }}}},
                  {"segment": 34, "color": {"r": {{ c34[0] }}, "g": {{ c34[1] }}, "b": {{ c34[2] }}}},
                  {"segment": 35, "color": {"r": {{ c35[0] }}, "g": {{ c35[1] }}, "b": {{ c35[2] }}}},
                  {"segment": 36, "color": {"r": {{ c36[0] }}, "g": {{ c36[1] }}, "b": {{ c36[2] }}}},
                  {"segment": 37, "color": {"r": {{ c37[0] }}, "g": {{ c37[1] }}, "b": {{ c37[2] }}}},
                  {"segment": 38, "color": {"r": {{ c38[0] }}, "g": {{ c38[1] }}, "b": {{ c38[2] }}}},
                  {"segment": 39, "color": {"r": {{ c39[0] }}, "g": {{ c39[1] }}, "b": {{ c39[2] }}}},
                  {"segment": 40, "color": {"r": {{ c40[0] }}, "g": {{ c40[1] }}, "b": {{ c40[2] }}}},
                  {"segment": 41, "color": {"r": {{ c41[0] }}, "g": {{ c41[1] }}, "b": {{ c41[2] }}}},
                  {"segment": 42, "color": {"r": {{ c42[0] }}, "g": {{ c42[1] }}, "b": {{ c42[2] }}}},
                  {"segment": 43, "color": {"r": {{ c43[0] }}, "g": {{ c43[1] }}, "b": {{ c43[2] }}}},
                  {"segment": 44, "color": {"r": {{ c44[0] }}, "g": {{ c44[1] }}, "b": {{ c44[2] }}}},
                  {"segment": 45, "color": {"r": {{ c45[0] }}, "g": {{ c45[1] }}, "b": {{ c45[2] }}}},
                  {"segment": 46, "color": {"r": {{ c46[0] }}, "g": {{ c46[1] }}, "b": {{ c46[2] }}}},
                  {"segment": 47, "color": {"r": {{ c47[0] }}, "g": {{ c47[1] }}, "b": {{ c47[2] }}}},
                  {"segment": 48, "color": {"r": {{ c48[0] }}, "g": {{ c48[1] }}, "b": {{ c48[2] }}}},
                  {"segment": 49, "color": {"r": {{ c49[0] }}, "g": {{ c49[1] }}, "b": {{ c49[2] }}}},
                  {"segment": 50, "color": {"r": {{ c50[0] }}, "g": {{ c50[1] }}, "b": {{ c50[2] }}}}
                ]
              }

mode: single
